image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install
    init: npm install && npm install --only=dev
  - name: Clasp
    command: npm install -g @google/clasp
    command: clasp login --no-localhost
