image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install
    init: npm install && npm install --only=dev
  - name: Clasp
    command: >
      npm install -g @google/clasp
      clasp login --no-localhost

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false